FROM public.ecr.aws/lambda/nodejs:24 AS build
WORKDIR /build
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts
COPY tsconfig.json tsconfig.build.json ./
COPY src ./src
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:24 AS production-dependencies
WORKDIR /build
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts

FROM public.ecr.aws/lambda/nodejs:24
ENV NODE_ENV=production
ENV NODE_OPTIONS=--experimental-require-module
COPY --from=production-dependencies /build/node_modules ${LAMBDA_TASK_ROOT}/node_modules
COPY --from=build /build/dist ${LAMBDA_TASK_ROOT}/dist
COPY drizzle ${LAMBDA_TASK_ROOT}/drizzle
CMD ["dist/lambda/http-entry.handler"]
